# -*- coding: utf-8 -*-
# DO NOT EDIT THIS FILE
# Natron PyPlug
# This file was automatically generated by Natron PyPlug exporter version 10.

# Hand-written code should be added in a separate file named DemopYpLUGExt.py
# See http://natron.readthedocs.org/en/master/devel/groups.html#adding-hand-written-code-callbacks-etc
# Note that Viewers are never exported

import NatronEngine
import sys

# Try to import the extensions file where callbacks and hand-written code should be located.
try:
    from DemopYpLUGExt import *
except ImportError:
    pass

def getPluginID():
    return "demoPYPLUG"

def getLabel():
    return "DemopYpLUG"

def getVersion():
    return 1

def getGrouping():
    return ""

def createInstance(app,group):
    # Create all nodes in the group

    # Create the parameters of the group node the same way we did for all internal nodes
    lastNode = group
    lastNode.setColor(0.7, 0.7, 0.7)

    # Create the user parameters
    lastNode.aaa = lastNode.createPageParam("aaa", "sss")
    param = lastNode.createIntParam("asda", "asdad")
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(100, 0)
    param.setDefaultValue(0, 0)
    param.restoreDefaultValue(0)

    # Add the param to the page
    lastNode.aaa.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    param.setValue(15, 0)
    lastNode.asda = param
    del param

    param = lastNode.createDouble2DParam("DirBlur1scale", "Scale")
    param.setMinimum(-10000, 0)
    param.setMaximum(10000, 0)
    param.setDisplayMinimum(0.1, 0)
    param.setDisplayMaximum(10, 0)
    param.setDefaultValue(1, 0)
    param.restoreDefaultValue(0)
    param.setMinimum(-10000, 1)
    param.setMaximum(10000, 1)
    param.setDisplayMinimum(0.1, 1)
    param.setDisplayMaximum(10, 1)
    param.setDefaultValue(1, 1)
    param.restoreDefaultValue(1)

    # Add the param to the page
    lastNode.aaa.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.DirBlur1scale = param
    del param

    # Refresh the GUI with the newly created parameters
    lastNode.setPagesOrder(['Node', 'Settings', 'aaa'])
    lastNode.refreshUserParamsGUI()
    del lastNode

    # Start of node "Output1"
    lastNode = app.createNode("fr.inria.built-in.Output", 1, group)
    lastNode.setLabel("Output")
    lastNode.setPosition(456, 150)
    lastNode.setSize(106, 33)
    lastNode.setColor(0.7, 0.7, 0.7)
    groupOutput1 = lastNode

    del lastNode
    # End of node "Output1"

    # Start of node "Input1"
    lastNode = app.createNode("fr.inria.built-in.Input", 1, group)
    lastNode.setScriptName("Input1")
    lastNode.setLabel("Input1")
    lastNode.setPosition(456, 53)
    lastNode.setSize(106, 33)
    lastNode.setColor(0.3, 0.5, 0.2)
    groupInput1 = lastNode

    del lastNode
    # End of node "Input1"

    # Start of node "DirBlur1"
    lastNode = app.createNode("net.sf.openfx.DirBlur", 1, group)
    lastNode.setScriptName("DirBlur1")
    lastNode.setLabel("DirBlur1")
    lastNode.setPosition(371, 88)
    lastNode.setSize(82, 33)
    lastNode.setColor(0.8, 0.5, 0.3)
    groupDirBlur1 = lastNode

    param = lastNode.getParam("hidpi")
    if param is not None:
        param.setValue(True)
        del param

    del lastNode
    # End of node "DirBlur1"

    # Start of node "DenoiseSharpen1"
    lastNode = app.createNode("net.sf.openfx.DenoiseSharpen", 1, group)
    lastNode.setScriptName("DenoiseSharpen1")
    lastNode.setLabel("DenoiseSharpen1")
    lastNode.setPosition(590, 162)
    lastNode.setSize(82, 56)
    lastNode.setColor(0.8, 0.5, 0.3)
    groupDenoiseSharpen1 = lastNode

    param = lastNode.getParam("noiseLevelGain")
    if param is not None:
        param.setValue(1.758, 0)
        del param

    param = lastNode.getParam("premult")
    if param is not None:
        param.setValue(True)
        del param

    del lastNode
    # End of node "DenoiseSharpen1"

    # Now that all nodes are created we can connect them together, restore expressions
    groupOutput1.connectInput(0, groupDenoiseSharpen1)
    groupDirBlur1.connectInput(0, groupInput1)
    groupDenoiseSharpen1.connectInput(0, groupInput1)

    param = groupDirBlur1.getParam("scale")
    group.getParam("DirBlur1scale").setAsAlias(param)
    del param

    try:
        extModule = sys.modules["DemopYpLUGExt"]
    except KeyError:
        extModule = None
    if extModule is not None and hasattr(extModule ,"createInstanceExt") and hasattr(extModule.createInstanceExt,"__call__"):
        extModule.createInstanceExt(app,group)
