# -*- coding: utf-8 -*-
# DO NOT EDIT THIS FILE
# Natron PyPlug
# This file was automatically generated by Natron PyPlug exporter version 10.

# Hand-written code should be added in a separate file named FinalReadNodeExt.py
# See http://natron.readthedocs.org/en/master/devel/groups.html#adding-hand-written-code-callbacks-etc
# Note that Viewers are never exported

import NatronEngine
import sys

# Try to import the extensions file where callbacks and hand-written code should be located.
try:
    from FinalReadNodeExt import *
except ImportError:
    pass

def getPluginID():
    return "final.read.node"

def getLabel():
    return "FinalReadNode"

def getVersion():
    return 1

def getGrouping():
    return ""

def createInstance(app,group):
    # Create all nodes in the group

    # Create the parameters of the group node the same way we did for all internal nodes
    lastNode = group
    lastNode.setColor(0.7, 0.7, 0.7)

    # Create the user parameters
    lastNode.ReadSettings = lastNode.createPageParam("ReadSettings", "Settings")
    param = lastNode.createInt2DParam("FrameRange1frameRange", "Frame Range")
    param.setDefaultValue(1, 0)
    param.restoreDefaultValue(0)
    param.setDefaultValue(1, 1)
    param.restoreDefaultValue(1)

    # Add the param to the page
    lastNode.ReadSettings.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(False)
    param.setValue(221, 1)
    lastNode.FrameRange1frameRange = param
    del param

    param = lastNode.createIntParam("TimeOffset1timeOffset", "Time Offset (Frames)")
    param.setDefaultValue(0, 0)
    param.restoreDefaultValue(0)

    # Add the param to the page
    lastNode.ReadSettings.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(False)
    lastNode.TimeOffset1timeOffset = param
    del param

    # Refresh the GUI with the newly created parameters
    lastNode.setPagesOrder(['Node', 'Settings', 'ReadSettings'])
    lastNode.refreshUserParamsGUI()
    del lastNode

    # Start of node "Output1"
    lastNode = app.createNode("fr.inria.built-in.Output", 1, group)
    lastNode.setLabel("Output")
    lastNode.setPosition(781, 230)
    lastNode.setSize(107, 34)
    lastNode.setColor(0.7, 0.7, 0.7)
    groupOutput1 = lastNode

    del lastNode
    # End of node "Output1"

    # Start of node "FrameRange1"
    lastNode = app.createNode("net.sf.openfx.FrameRange", 1, group)
    lastNode.setScriptName("FrameRange1")
    lastNode.setLabel("FrameRange1")
    lastNode.setPosition(793, -2)
    lastNode.setSize(86, 56)
    lastNode.setColor(0.7, 0.65, 0.35)
    groupFrameRange1 = lastNode

    param = lastNode.getParam("frameRange")
    if param is not None:
        param.setValue(221, 1)
        del param

    del lastNode
    # End of node "FrameRange1"

    # Start of node "TimeOffset1"
    lastNode = app.createNode("net.sf.openfx.timeOffset", 1, group)
    lastNode.setScriptName("TimeOffset1")
    lastNode.setLabel("TimeOffset1")
    lastNode.setPosition(793, 84)
    lastNode.setSize(83, 33)
    lastNode.setColor(0.7, 0.65, 0.35)
    groupTimeOffset1 = lastNode

    del lastNode
    # End of node "TimeOffset1"

    # Start of node "Transform1"
    lastNode = app.createNode("net.sf.openfx.TransformPlugin", 1, group)
    lastNode.setScriptName("Transform1")
    lastNode.setLabel("Transform1")
    lastNode.setPosition(793, 146)
    lastNode.setSize(83, 33)
    lastNode.setColor(0.7, 0.3, 0.1)
    groupTransform1 = lastNode

    del lastNode
    # End of node "Transform1"

    # Start of node "Read1"
    lastNode = app.createNode("fr.inria.built-in.Read", 1, group)
    lastNode.setScriptName("Read1")
    lastNode.setLabel("Read1")
    lastNode.setPosition(769, -138)
    lastNode.setSize(225, 79)
    lastNode.setColor(0.7, 0.7, 0.7)
    groupRead1 = lastNode

    param = lastNode.getParam("decodingPluginID")
    if param is not None:
        param.setValue("fr.inria.openfx.ReadFFmpeg")
        del param

    param = lastNode.getParam("filename")
    if param is not None:
        param.setValue("/home/npittas/Videos/VFX_Shot_0200_comp_v001.mov")
        del param

    param = lastNode.getParam("lastFrame")
    if param is not None:
        param.setValue(221, 0)
        del param

    param = lastNode.getParam("timeDomainUserEdited")
    if param is not None:
        param.setValue(True)
        del param

    param = lastNode.getParam("filePremult")
    if param is not None:
        param.set("unpremult")
        del param

    param = lastNode.getParam("ParamExistingInstance")
    if param is not None:
        param.setValue(True)
        del param

    param = lastNode.getParam("ocioInputSpace")
    if param is not None:
        param.setValue("Rec709")
        del param

    del lastNode
    # End of node "Read1"

    # Now that all nodes are created we can connect them together, restore expressions
    groupOutput1.connectInput(0, groupTransform1)
    groupFrameRange1.connectInput(0, groupRead1)
    groupTimeOffset1.connectInput(0, groupFrameRange1)
    groupTransform1.connectInput(0, groupTimeOffset1)

    param = groupFrameRange1.getParam("frameRange")
    group.getParam("FrameRange1frameRange").setAsAlias(param)
    del param
    param = groupTimeOffset1.getParam("timeOffset")
    group.getParam("TimeOffset1timeOffset").setAsAlias(param)
    del param

    try:
        extModule = sys.modules["FinalReadNodeExt"]
    except KeyError:
        extModule = None
    if extModule is not None and hasattr(extModule ,"createInstanceExt") and hasattr(extModule.createInstanceExt,"__call__"):
        extModule.createInstanceExt(app,group)
