# -*- coding: utf-8 -*-
# DO NOT EDIT THIS FILE
# Natron PyPlug
# This file was automatically generated by Natron PyPlug exporter version 10.

# Hand-written code should be added in a separate file named FinalPluginExt.py
# See http://natron.readthedocs.org/en/master/devel/groups.html#adding-hand-written-code-callbacks-etc
# Note that Viewers are never exported

import NatronEngine
import sys

# Try to import the extensions file where callbacks and hand-written code should be located.
try:
    from FinalPluginExt import *
except ImportError:
    pass

def getPluginID():
    return "Final.Plugin"

def getLabel():
    return "FinalPlugin"

def getVersion():
    return 1

def getGrouping():
    return ""

def createInstance(app,group):
    # Create all nodes in the group

    # Create the parameters of the group node the same way we did for all internal nodes
    lastNode = group
    lastNode.setColor(0.7, 0.7, 0.7)

    # Create the user parameters
    lastNode.ReadSettings = lastNode.createPageParam("ReadSettings", "Settings")
    param = lastNode.createSeparatorParam("FramesInOut", "Frames In/Out")

    # Add the param to the page
    lastNode.ReadSettings.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setPersistent(False)
    param.setEvaluateOnChange(False)
    lastNode.FramesInOut = param
    del param

    param = lastNode.createInt2DParam("FrameRange1frameRange", "Frame Range")
    param.setDefaultValue(1, 0)
    param.restoreDefaultValue(0)
    param.setDefaultValue(1, 1)
    param.restoreDefaultValue(1)

    # Add the param to the page
    lastNode.ReadSettings.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(False)
    param.setValue(221, 1)
    lastNode.FrameRange1frameRange = param
    del param

    param = lastNode.createSeparatorParam("TimeOffset", "Time Offset")

    # Add the param to the page
    lastNode.ReadSettings.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setPersistent(False)
    param.setEvaluateOnChange(False)
    lastNode.TimeOffset = param
    del param

    param = lastNode.createIntParam("TimeOffset1timeOffset", "Time Offset (Frames)")
    param.setDefaultValue(0, 0)
    param.restoreDefaultValue(0)

    # Add the param to the page
    lastNode.ReadSettings.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(False)
    lastNode.TimeOffset1timeOffset = param
    del param

    param = lastNode.createSeparatorParam("Position", "Position")

    # Add the param to the page
    lastNode.ReadSettings.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setPersistent(False)
    param.setEvaluateOnChange(False)
    lastNode.Position = param
    del param

    param = lastNode.createDouble2DParam("Transform1translate", "Translate")
    param.setDisplayMinimum(-10000, 0)
    param.setDisplayMaximum(10000, 0)
    param.setDisplayMinimum(-10000, 1)
    param.setDisplayMaximum(10000, 1)

    # Add the param to the page
    lastNode.ReadSettings.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Transform1translate = param
    del param

    param = lastNode.createSeparatorParam("Rotation", "Rotation")

    # Add the param to the page
    lastNode.ReadSettings.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setPersistent(False)
    param.setEvaluateOnChange(False)
    lastNode.Rotation = param
    del param

    param = lastNode.createDoubleParam("Transform1rotate", "Rotate")
    param.setDisplayMinimum(-180, 0)
    param.setDisplayMaximum(180, 0)

    # Add the param to the page
    lastNode.ReadSettings.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Transform1rotate = param
    del param

    param = lastNode.createSeparatorParam("Scale", "Scale")

    # Add the param to the page
    lastNode.ReadSettings.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setPersistent(False)
    param.setEvaluateOnChange(False)
    lastNode.Scale = param
    del param

    param = lastNode.createDouble2DParam("Transform1scale", "Scale")
    param.setMinimum(-10000, 0)
    param.setMaximum(10000, 0)
    param.setDisplayMinimum(0.1, 0)
    param.setDisplayMaximum(10, 0)
    param.setDefaultValue(1, 0)
    param.restoreDefaultValue(0)
    param.setMinimum(-10000, 1)
    param.setMaximum(10000, 1)
    param.setDisplayMinimum(0.1, 1)
    param.setDisplayMaximum(10, 1)
    param.setDefaultValue(1, 1)
    param.restoreDefaultValue(1)

    # Add the param to the page
    lastNode.ReadSettings.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Transform1scale = param
    del param

    param = lastNode.createSeparatorParam("Skew", "Skew")

    # Add the param to the page
    lastNode.ReadSettings.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setPersistent(False)
    param.setEvaluateOnChange(False)
    lastNode.Skew = param
    del param

    param = lastNode.createDoubleParam("Transform1skewX", "Skew X")
    param.setDisplayMinimum(-1, 0)
    param.setDisplayMaximum(1, 0)

    # Add the param to the page
    lastNode.ReadSettings.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Transform1skewX = param
    del param

    param = lastNode.createDoubleParam("Transform1skewY", "Skew Y")
    param.setDisplayMinimum(-1, 0)
    param.setDisplayMaximum(1, 0)

    # Add the param to the page
    lastNode.ReadSettings.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Transform1skewY = param
    del param

    param = lastNode.createDouble2DParam("Transform1center", "Center")
    param.setDisplayMinimum(-10000, 0)
    param.setDisplayMaximum(10000, 0)
    param.setDefaultValue(0.5, 0)
    param.restoreDefaultValue(0)
    param.setDisplayMinimum(-10000, 1)
    param.setDisplayMaximum(10000, 1)
    param.setDefaultValue(0.5, 1)
    param.restoreDefaultValue(1)

    # Add the param to the page
    lastNode.ReadSettings.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    param.setValue(2304, 0)
    param.setValue(791, 1)
    lastNode.Transform1center = param
    del param

    param = lastNode.createSeparatorParam("TransformSettings", "Settings")

    # Add the param to the page
    lastNode.ReadSettings.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setPersistent(False)
    param.setEvaluateOnChange(False)
    lastNode.TransformSettings = param
    del param

    param = lastNode.createChoiceParam("Transform1filter", "Filter")
    param.setDefaultValue(3)
    param.restoreDefaultValue()

    # Add the param to the page
    lastNode.ReadSettings.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Transform1filter = param
    del param

    param = lastNode.createSeparatorParam("MotionBlur", "Motion Blur")

    # Add the param to the page
    lastNode.ReadSettings.addParam(param)

    # Set param properties
    param.setHelp("")
    param.setAddNewLine(True)
    param.setPersistent(False)
    param.setEvaluateOnChange(False)
    lastNode.MotionBlur = param
    del param

    param = lastNode.createDoubleParam("Transform1motionBlur", "Motion Blur")
    param.setMinimum(0, 0)
    param.setMaximum(100, 0)
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(4, 0)

    # Add the param to the page
    lastNode.ReadSettings.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Transform1motionBlur = param
    del param

    param = lastNode.createBooleanParam("Transform1directionalBlur", "Directional Blur Mode")

    # Add the param to the page
    lastNode.ReadSettings.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Transform1directionalBlur = param
    del param

    param = lastNode.createDoubleParam("Transform1shutter", "Shutter")
    param.setMinimum(0, 0)
    param.setMaximum(2, 0)
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(2, 0)
    param.setDefaultValue(0.5, 0)
    param.restoreDefaultValue(0)

    # Add the param to the page
    lastNode.ReadSettings.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Transform1shutter = param
    del param

    param = lastNode.createChoiceParam("Transform1shutterOffset", "Shutter Offset")
    param.setDefaultValue(1)
    param.restoreDefaultValue()

    # Add the param to the page
    lastNode.ReadSettings.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Transform1shutterOffset = param
    del param

    param = lastNode.createDoubleParam("Transform1shutterCustomOffset", "Custom Offset")
    param.setMinimum(-1, 0)
    param.setMaximum(1, 0)
    param.setDisplayMinimum(-1, 0)
    param.setDisplayMaximum(1, 0)

    # Add the param to the page
    lastNode.ReadSettings.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Transform1shutterCustomOffset = param
    del param

    # Refresh the GUI with the newly created parameters
    lastNode.setPagesOrder(['ReadSettings', 'Node', 'Settings'])
    lastNode.refreshUserParamsGUI()
    del lastNode

    # Start of node "Output1"
    lastNode = app.createNode("fr.inria.built-in.Output", 1, group)
    lastNode.setLabel("Output")
    lastNode.setPosition(781, 230)
    lastNode.setSize(106, 33)
    lastNode.setColor(0.7, 0.7, 0.7)
    groupOutput1 = lastNode

    del lastNode
    # End of node "Output1"

    # Start of node "FrameRange1"
    lastNode = app.createNode("net.sf.openfx.FrameRange", 1, group)
    lastNode.setScriptName("FrameRange1")
    lastNode.setLabel("FrameRange1")
    lastNode.setPosition(793, -2)
    lastNode.setSize(82, 56)
    lastNode.setColor(0.7, 0.65, 0.35)
    groupFrameRange1 = lastNode

    param = lastNode.getParam("frameRange")
    if param is not None:
        param.setValue(221, 1)
        del param

    del lastNode
    # End of node "FrameRange1"

    # Start of node "TimeOffset1"
    lastNode = app.createNode("net.sf.openfx.timeOffset", 1, group)
    lastNode.setScriptName("TimeOffset1")
    lastNode.setLabel("TimeOffset1")
    lastNode.setPosition(793, 84)
    lastNode.setSize(82, 33)
    lastNode.setColor(0.7, 0.65, 0.35)
    groupTimeOffset1 = lastNode

    del lastNode
    # End of node "TimeOffset1"

    # Start of node "Transform1"
    lastNode = app.createNode("net.sf.openfx.TransformPlugin", 1, group)
    lastNode.setScriptName("Transform1")
    lastNode.setLabel("Transform1")
    lastNode.setPosition(793, 146)
    lastNode.setSize(82, 33)
    lastNode.setColor(0.7, 0.3, 0.1)
    groupTransform1 = lastNode

    del lastNode
    # End of node "Transform1"

    # Start of node "Read1"
    lastNode = app.createNode("fr.inria.built-in.Read", 1, group)
    lastNode.setScriptName("Read1")
    lastNode.setLabel("Read1")
    lastNode.setPosition(769, -138)
    lastNode.setSize(130, 79)
    lastNode.setColor(0.7, 0.7, 0.7)
    groupRead1 = lastNode

    param = lastNode.getParam("decodingPluginID")
    if param is not None:
        param.setValue("fr.inria.openfx.ReadFFmpeg")
        del param

    param = lastNode.getParam("filename")
    if param is not None:
        param.setValue("/home/npittas/Videos/VFX_Shot_0200_comp_v001.mov")
        del param

    param = lastNode.getParam("lastFrame")
    if param is not None:
        param.setValue(221, 0)
        del param

    param = lastNode.getParam("timeDomainUserEdited")
    if param is not None:
        param.setValue(True)
        del param

    param = lastNode.getParam("filePremult")
    if param is not None:
        param.set("unpremult")
        del param

    param = lastNode.getParam("ParamExistingInstance")
    if param is not None:
        param.setValue(True)
        del param

    param = lastNode.getParam("ocioInputSpace")
    if param is not None:
        param.setValue("Rec709")
        del param

    del lastNode
    # End of node "Read1"

    # Now that all nodes are created we can connect them together, restore expressions
    groupOutput1.connectInput(0, groupTransform1)
    groupFrameRange1.connectInput(0, groupRead1)
    groupTimeOffset1.connectInput(0, groupFrameRange1)
    groupTransform1.connectInput(0, groupTimeOffset1)

    param = groupFrameRange1.getParam("frameRange")
    group.getParam("FrameRange1frameRange").setAsAlias(param)
    del param
    param = groupTimeOffset1.getParam("timeOffset")
    group.getParam("TimeOffset1timeOffset").setAsAlias(param)
    del param
    param = groupTransform1.getParam("translate")
    group.getParam("Transform1translate").setAsAlias(param)
    del param
    param = groupTransform1.getParam("rotate")
    group.getParam("Transform1rotate").setAsAlias(param)
    del param
    param = groupTransform1.getParam("scale")
    group.getParam("Transform1scale").setAsAlias(param)
    del param
    param = groupTransform1.getParam("skewX")
    group.getParam("Transform1skewX").setAsAlias(param)
    del param
    param = groupTransform1.getParam("skewY")
    group.getParam("Transform1skewY").setAsAlias(param)
    del param
    param = groupTransform1.getParam("center")
    group.getParam("Transform1center").setAsAlias(param)
    del param
    param = groupTransform1.getParam("filter")
    group.getParam("Transform1filter").setAsAlias(param)
    del param
    param = groupTransform1.getParam("motionBlur")
    group.getParam("Transform1motionBlur").setAsAlias(param)
    del param
    param = groupTransform1.getParam("directionalBlur")
    group.getParam("Transform1directionalBlur").setAsAlias(param)
    del param
    param = groupTransform1.getParam("shutter")
    group.getParam("Transform1shutter").setAsAlias(param)
    del param
    param = groupTransform1.getParam("shutterOffset")
    group.getParam("Transform1shutterOffset").setAsAlias(param)
    del param
    param = groupTransform1.getParam("shutterCustomOffset")
    group.getParam("Transform1shutterCustomOffset").setAsAlias(param)
    del param

    try:
        extModule = sys.modules["FinalPluginExt"]
    except KeyError:
        extModule = None
    if extModule is not None and hasattr(extModule ,"createInstanceExt") and hasattr(extModule.createInstanceExt,"__call__"):
        extModule.createInstanceExt(app,group)
