# -*- coding: utf-8 -*-
# DO NOT EDIT THIS FILE
# Natron PyPlug
# This file was automatically generated by Natron PyPlug exporter version 10.

# Hand-written code should be added in a separate file named TxtGroupExt.py
# See http://natron.readthedocs.org/en/master/devel/groups.html#adding-hand-written-code-callbacks-etc
# Note that Viewers are never exported

import NatronEngine
import sys

# Try to import the extensions file where callbacks and hand-written code should be located.
try:
    from TxtGroupExt import *
except ImportError:
    pass

def getPluginID():
    return "text.node.demo"

def getLabel():
    return "TxtGroup"

def getVersion():
    return 1

def getGrouping():
    return "T"

def createInstance(app,group):
    # Create all nodes in the group

    # Create the parameters of the group node the same way we did for all internal nodes
    lastNode = group
    lastNode.setColor(0.7, 0.7, 0.7)

    # Create the user parameters
    lastNode.userNatron = lastNode.createPageParam("userNatron", "User")
    param = lastNode.createDoubleParam("Text1rotate", "Rotate")
    param.setDisplayMinimum(-180, 0)
    param.setDisplayMaximum(180, 0)

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Text1rotate = param
    del param

    param = lastNode.createDouble2DParam("Text1scale", "Scale")
    param.setMinimum(-10000, 0)
    param.setMaximum(10000, 0)
    param.setDisplayMinimum(0.1, 0)
    param.setDisplayMaximum(10, 0)
    param.setDefaultValue(1, 0)
    param.restoreDefaultValue(0)
    param.setMinimum(-10000, 1)
    param.setMaximum(10000, 1)
    param.setDisplayMinimum(0.1, 1)
    param.setDisplayMaximum(10, 1)
    param.setDefaultValue(1, 1)
    param.restoreDefaultValue(1)

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Text1scale = param
    del param

    param = lastNode.createBooleanParam("Text1uniform", "Uniform")

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Text1uniform = param
    del param

    param = lastNode.createDoubleParam("Text1skewX", "Skew X")
    param.setDisplayMinimum(-1, 0)
    param.setDisplayMaximum(1, 0)

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Text1skewX = param
    del param

    param = lastNode.createDoubleParam("Text1skewY", "Skew Y")
    param.setDisplayMinimum(-1, 0)
    param.setDisplayMaximum(1, 0)

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Text1skewY = param
    del param

    param = lastNode.createChoiceParam("Text1skewOrder", "Skew Order")

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Text1skewOrder = param
    del param

    param = lastNode.createDoubleParam("Text1transformAmount", "Amount")
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(1, 0)
    param.setDefaultValue(1, 0)
    param.restoreDefaultValue(0)

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Text1transformAmount = param
    del param

    param = lastNode.createDouble2DParam("Text1center", "Center")
    param.setDisplayMinimum(-10000, 0)
    param.setDisplayMaximum(10000, 0)
    param.setDefaultValue(0.5, 0)
    param.restoreDefaultValue(0)
    param.setDisplayMinimum(-10000, 1)
    param.setDisplayMaximum(10000, 1)
    param.setDefaultValue(0.5, 1)
    param.restoreDefaultValue(1)

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    param.setValue(890, 0)
    param.setValue(540, 1)
    lastNode.Text1center = param
    del param

    param = lastNode.createBooleanParam("Text1interactive", "Interactive Update")
    param.setDefaultValue(True)
    param.restoreDefaultValue()

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setEvaluateOnChange(False)
    param.setAnimationEnabled(False)
    lastNode.Text1interactive = param
    del param

    param = lastNode.createBooleanParam("Text1hidpi", "HiDPI")

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setEvaluateOnChange(False)
    param.setAnimationEnabled(False)
    param.setValue(True)
    lastNode.Text1hidpi = param
    del param

    param = lastNode.createBooleanParam("Text1transform", "Transform")
    param.setDefaultValue(True)
    param.restoreDefaultValue()

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(False)
    lastNode.Text1transform = param
    del param

    param = lastNode.createBooleanParam("Text1autoSize", "Auto size")

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(False)
    lastNode.Text1autoSize = param
    del param

    param = lastNode.createBooleanParam("Text1centerInteract", "Center Interact")

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(False)
    lastNode.Text1centerInteract = param
    del param

    param = lastNode.createInt2DParam("Text1canvas", "Canvas size")
    param.setMinimum(0, 0)
    param.setMaximum(10000, 0)
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(4000, 0)
    param.setDefaultValue(0, 0)
    param.restoreDefaultValue(0)
    param.setMinimum(0, 1)
    param.setMaximum(10000, 1)
    param.setDisplayMinimum(0, 1)
    param.setDisplayMaximum(4000, 1)
    param.setDefaultValue(0, 1)
    param.restoreDefaultValue(1)

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(False)
    lastNode.Text1canvas = param
    del param

    param = lastNode.createBooleanParam("Text1markup", "Markup")

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(False)
    lastNode.Text1markup = param
    del param

    param = lastNode.createFileParam("Text1file", "Text File")
    param.setSequenceEnabled(False)

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(False)
    lastNode.Text1file = param
    del param

    param = lastNode.createFileParam("Text1subtitle", "Subtitle File")
    param.setSequenceEnabled(False)

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(False)
    lastNode.Text1subtitle = param
    del param

    param = lastNode.createDoubleParam("Text1fps", "Frame Rate")
    param.setMinimum(-1.79769e+308, 0)
    param.setMaximum(1.79769e+308, 0)
    param.setDisplayMinimum(-1.79769e+308, 0)
    param.setDisplayMaximum(1.79769e+308, 0)
    param.setDefaultValue(24, 0)
    param.restoreDefaultValue(0)

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(False)
    lastNode.Text1fps = param
    del param

    param = lastNode.createStringParam("Text1text", "Text")
    param.setType(NatronEngine.StringParam.TypeEnum.eStringTypeMultiLine)
    param.setDefaultValue("Enter text")
    param.restoreDefaultValue()

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Text1text = param
    del param

    param = lastNode.createBooleanParam("Text1justify", "Justify")

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(False)
    lastNode.Text1justify = param
    del param

    param = lastNode.createChoiceParam("Text1wrap", "Wrap")

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(False)
    lastNode.Text1wrap = param
    del param

    param = lastNode.createChoiceParam("Text1align", "Horizontal align")

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(False)
    lastNode.Text1align = param
    del param

    param = lastNode.createChoiceParam("Text1valign", "Vertical align")

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(False)
    lastNode.Text1valign = param
    del param

    param = lastNode.createChoiceParam("Text1name", "Select font")
    param.setDefaultValue(11)
    param.restoreDefaultValue()

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(False)
    lastNode.Text1name = param
    del param

    param = lastNode.createFileParam("Text1custom", "Custom font(s)")
    param.setSequenceEnabled(False)

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(False)
    lastNode.Text1custom = param
    del param

    param = lastNode.createStringParam("Text1font", "Font family")
    param.setType(NatronEngine.StringParam.TypeEnum.eStringTypeDefault)
    param.setDefaultValue("Arial")
    param.restoreDefaultValue()

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Text1font = param
    del param

    param = lastNode.createIntParam("Text1size", "Font size")
    param.setMinimum(1, 0)
    param.setMaximum(10000, 0)
    param.setDisplayMinimum(1, 0)
    param.setDisplayMaximum(500, 0)
    param.setDefaultValue(64, 0)
    param.restoreDefaultValue(0)

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    param.setValue(84, 0)
    lastNode.Text1size = param
    del param

    param = lastNode.createColorParam("Text1color", "Font color", True)
    param.setMinimum(-1.79769e+308, 0)
    param.setMaximum(1.79769e+308, 0)
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(1, 0)
    param.setDefaultValue(1, 0)
    param.restoreDefaultValue(0)
    param.setMinimum(-1.79769e+308, 1)
    param.setMaximum(1.79769e+308, 1)
    param.setDisplayMinimum(0, 1)
    param.setDisplayMaximum(1, 1)
    param.setDefaultValue(1, 1)
    param.restoreDefaultValue(1)
    param.setMinimum(-1.79769e+308, 2)
    param.setMaximum(1.79769e+308, 2)
    param.setDisplayMinimum(0, 2)
    param.setDisplayMaximum(1, 2)
    param.setDefaultValue(1, 2)
    param.restoreDefaultValue(2)
    param.setMinimum(-1.79769e+308, 3)
    param.setMaximum(1.79769e+308, 3)
    param.setDisplayMinimum(0, 3)
    param.setDisplayMaximum(1, 3)
    param.setDefaultValue(1, 3)
    param.restoreDefaultValue(3)

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Text1color = param
    del param

    param = lastNode.createColorParam("Text1backgroundColor", "Background Color", True)
    param.setMinimum(-1.79769e+308, 0)
    param.setMaximum(1.79769e+308, 0)
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(1, 0)
    param.setMinimum(-1.79769e+308, 1)
    param.setMaximum(1.79769e+308, 1)
    param.setDisplayMinimum(0, 1)
    param.setDisplayMaximum(1, 1)
    param.setMinimum(-1.79769e+308, 2)
    param.setMaximum(1.79769e+308, 2)
    param.setDisplayMinimum(0, 2)
    param.setDisplayMaximum(1, 2)
    param.setMinimum(-1.79769e+308, 3)
    param.setMaximum(1.79769e+308, 3)
    param.setDisplayMinimum(0, 3)
    param.setDisplayMaximum(1, 3)

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Text1backgroundColor = param
    del param

    param = lastNode.createIntParam("Text1letterSpace", "Letter spacing")
    param.setMinimum(-10000, 0)
    param.setMaximum(10000, 0)
    param.setDisplayMinimum(-250, 0)
    param.setDisplayMaximum(250, 0)
    param.setDefaultValue(0, 0)
    param.restoreDefaultValue(0)

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Text1letterSpace = param
    del param

    param = lastNode.createChoiceParam("Text1hintStyle", "Hint style")

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(False)
    lastNode.Text1hintStyle = param
    del param

    param = lastNode.createChoiceParam("Text1hintMetrics", "Hint metrics")

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(False)
    lastNode.Text1hintMetrics = param
    del param

    param = lastNode.createChoiceParam("Text1antialiasing", "Antialiasing")

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(False)
    lastNode.Text1antialiasing = param
    del param

    param = lastNode.createChoiceParam("Text1subpixel", "Subpixel")

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(False)
    lastNode.Text1subpixel = param
    del param

    param = lastNode.createChoiceParam("Text1style", "Style")

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(False)
    lastNode.Text1style = param
    del param

    param = lastNode.createChoiceParam("Text1weight", "Weight")
    param.setDefaultValue(5)
    param.restoreDefaultValue()

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(False)
    lastNode.Text1weight = param
    del param

    param = lastNode.createChoiceParam("Text1stretch", "Stretch")
    param.setDefaultValue(4)
    param.restoreDefaultValue()

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(False)
    lastNode.Text1stretch = param
    del param

    param = lastNode.createDoubleParam("Text1strokeSize", "Stroke size")
    param.setMinimum(0, 0)
    param.setMaximum(500, 0)
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(100, 0)

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Text1strokeSize = param
    del param

    param = lastNode.createColorParam("Text1strokeColor", "Stroke color", True)
    param.setMinimum(-1.79769e+308, 0)
    param.setMaximum(1.79769e+308, 0)
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(1, 0)
    param.setDefaultValue(1, 0)
    param.restoreDefaultValue(0)
    param.setMinimum(-1.79769e+308, 1)
    param.setMaximum(1.79769e+308, 1)
    param.setDisplayMinimum(0, 1)
    param.setDisplayMaximum(1, 1)
    param.setMinimum(-1.79769e+308, 2)
    param.setMaximum(1.79769e+308, 2)
    param.setDisplayMinimum(0, 2)
    param.setDisplayMaximum(1, 2)
    param.setMinimum(-1.79769e+308, 3)
    param.setMaximum(1.79769e+308, 3)
    param.setDisplayMinimum(0, 3)
    param.setDisplayMaximum(1, 3)
    param.setDefaultValue(1, 3)
    param.restoreDefaultValue(3)

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Text1strokeColor = param
    del param

    param = lastNode.createIntParam("Text1strokeDash", "Stroke dash length")
    param.setMinimum(0, 0)
    param.setMaximum(100, 0)
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(10, 0)
    param.setDefaultValue(0, 0)
    param.restoreDefaultValue(0)

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Text1strokeDash = param
    del param

    param = lastNode.createDouble3DParam("Text1strokeDashPattern", "Stroke dash pattern")
    param.setMinimum(-1.79769e+308, 0)
    param.setMaximum(1.79769e+308, 0)
    param.setDisplayMinimum(-1.79769e+308, 0)
    param.setDisplayMaximum(1.79769e+308, 0)
    param.setDefaultValue(1, 0)
    param.restoreDefaultValue(0)
    param.setMinimum(-1.79769e+308, 1)
    param.setMaximum(1.79769e+308, 1)
    param.setDisplayMinimum(-1.79769e+308, 1)
    param.setDisplayMaximum(1.79769e+308, 1)
    param.setMinimum(-1.79769e+308, 2)
    param.setMaximum(1.79769e+308, 2)
    param.setDisplayMinimum(-1.79769e+308, 2)
    param.setDisplayMaximum(1.79769e+308, 2)

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Text1strokeDashPattern = param
    del param

    param = lastNode.createDoubleParam("Text1circleRadius", "Circle radius")
    param.setMinimum(0, 0)
    param.setMaximum(10000, 0)
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(1000, 0)

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Text1circleRadius = param
    del param

    param = lastNode.createIntParam("Text1circleWords", "Circle Words")
    param.setMinimum(1, 0)
    param.setMaximum(1000, 0)
    param.setDisplayMinimum(1, 0)
    param.setDisplayMaximum(100, 0)
    param.setDefaultValue(10, 0)
    param.restoreDefaultValue(0)

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Text1circleWords = param
    del param

    param = lastNode.createDoubleParam("Text1arcRadius", "Arc Radius")
    param.setMinimum(0, 0)
    param.setMaximum(10000, 0)
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(1000, 0)
    param.setDefaultValue(100, 0)
    param.restoreDefaultValue(0)

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Text1arcRadius = param
    del param

    param = lastNode.createDoubleParam("Text1arcAngle", "Arc Angle")
    param.setMinimum(0, 0)
    param.setMaximum(360, 0)
    param.setDisplayMinimum(0, 0)
    param.setDisplayMaximum(360, 0)

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Text1arcAngle = param
    del param

    param = lastNode.createDoubleParam("Text1scrollX", "Scroll X")
    param.setMinimum(-10000, 0)
    param.setMaximum(10000, 0)
    param.setDisplayMinimum(-4000, 0)
    param.setDisplayMaximum(4000, 0)

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Text1scrollX = param
    del param

    param = lastNode.createDoubleParam("Text1scrollY", "Scroll Y")
    param.setMinimum(-10000, 0)
    param.setMaximum(10000, 0)
    param.setDisplayMinimum(-4000, 0)
    param.setDisplayMaximum(4000, 0)

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(True)
    lastNode.Text1scrollY = param
    del param

    param = lastNode.createInt2DParam("Text1frameRange", "Frame Range")
    param.setDefaultValue(1, 0)
    param.restoreDefaultValue(0)
    param.setDefaultValue(1, 1)
    param.restoreDefaultValue(1)

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(False)
    lastNode.Text1frameRange = param
    del param

    param = lastNode.createChoiceParam("Text1channels", "Output Layer")

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(False)
    lastNode.Text1channels = param
    del param

    param = lastNode.createBooleanParam("Text1processAllPlanes", "All Planes")
    param.setDefaultValue(True)
    param.restoreDefaultValue()

    # Add the param to the page
    lastNode.userNatron.addParam(param)

    # Set param properties
    param.setAddNewLine(True)
    param.setAnimationEnabled(False)
    lastNode.Text1processAllPlanes = param
    del param

    # Refresh the GUI with the newly created parameters
    lastNode.setPagesOrder(['Node', 'Settings', 'userNatron'])
    lastNode.refreshUserParamsGUI()
    del lastNode

    # Start of node "Output1"
    lastNode = app.createNode("fr.inria.built-in.Output", 1, group)
    if lastNode is None:
        raise RuntimeError("Failed to create required node with plug-in ID fr.inria.built-in.Output. Check that the corresponding OpenFX/PyPlug provider is installed and that its shared-library dependencies load correctly.")
    lastNode.setLabel("Output")
    lastNode.setPosition(256, 365)
    lastNode.setSize(107, 34)
    lastNode.setColor(0.7, 0.7, 0.7)
    groupOutput1 = lastNode

    del lastNode
    # End of node "Output1"

    # Start of node "Text1"
    lastNode = app.createNode("net.fxarena.openfx.Text", 6, group)
    if lastNode is None:
        raise RuntimeError("Failed to create required node with plug-in ID net.fxarena.openfx.Text. Check that the corresponding OpenFX/PyPlug provider is installed and that its shared-library dependencies load correctly.")
    lastNode.setScriptName("Text1")
    lastNode.setLabel("Text1")
    lastNode.setPosition(256, 226)
    lastNode.setSize(107, 33)
    lastNode.setColor(0.3, 0.5, 0.2)
    groupText1 = lastNode

    param = lastNode.getParam("rotate")
    if param is not None:
        param.setValue(0, 0)
        del param

    param = lastNode.getParam("scale")
    if param is not None:
        param.setValue(1, 0)
        param.setValue(1, 1)
        del param

    param = lastNode.getParam("transformAmount")
    if param is not None:
        param.setValue(1, 0)
        del param

    param = lastNode.getParam("center")
    if param is not None:
        param.setValue(890, 0)
        param.setValue(540, 1)
        del param

    param = lastNode.getParam("hidpi")
    if param is not None:
        param.setValue(True)
        del param

    param = lastNode.getParam("autoSize")
    if param is not None:
        param.setValue(False)
        del param

    param = lastNode.getParam("file")
    if param is not None:
        param.setValue("")
        del param

    param = lastNode.getParam("subtitle")
    if param is not None:
        param.setValue("")
        del param

    param = lastNode.getParam("custom")
    if param is not None:
        param.setValue("")
        del param

    param = lastNode.getParam("size")
    if param is not None:
        param.setValue(84, 0)
        del param

    del lastNode
    # End of node "Text1"

    # Now that all nodes are created we can connect them together, restore expressions
    groupOutput1.connectInput(0, groupText1)

    param = groupText1.getParam("rotate")
    group.getParam("Text1rotate").setAsAlias(param)
    del param
    param = groupText1.getParam("scale")
    group.getParam("Text1scale").setAsAlias(param)
    del param
    param = groupText1.getParam("uniform")
    group.getParam("Text1uniform").setAsAlias(param)
    del param
    param = groupText1.getParam("skewX")
    group.getParam("Text1skewX").setAsAlias(param)
    del param
    param = groupText1.getParam("skewY")
    group.getParam("Text1skewY").setAsAlias(param)
    del param
    param = groupText1.getParam("skewOrder")
    group.getParam("Text1skewOrder").setAsAlias(param)
    del param
    param = groupText1.getParam("transformAmount")
    group.getParam("Text1transformAmount").setAsAlias(param)
    del param
    param = groupText1.getParam("center")
    group.getParam("Text1center").setAsAlias(param)
    del param
    param = groupText1.getParam("interactive")
    group.getParam("Text1interactive").setAsAlias(param)
    del param
    param = groupText1.getParam("hidpi")
    group.getParam("Text1hidpi").setAsAlias(param)
    del param
    param = groupText1.getParam("transform")
    group.getParam("Text1transform").setAsAlias(param)
    del param
    param = groupText1.getParam("autoSize")
    group.getParam("Text1autoSize").setAsAlias(param)
    del param
    param = groupText1.getParam("centerInteract")
    group.getParam("Text1centerInteract").setAsAlias(param)
    del param
    param = groupText1.getParam("canvas")
    group.getParam("Text1canvas").setAsAlias(param)
    del param
    param = groupText1.getParam("markup")
    group.getParam("Text1markup").setAsAlias(param)
    del param
    param = groupText1.getParam("file")
    group.getParam("Text1file").setAsAlias(param)
    del param
    param = groupText1.getParam("subtitle")
    group.getParam("Text1subtitle").setAsAlias(param)
    del param
    param = groupText1.getParam("fps")
    group.getParam("Text1fps").setAsAlias(param)
    del param
    param = groupText1.getParam("text")
    group.getParam("Text1text").setAsAlias(param)
    del param
    param = groupText1.getParam("justify")
    group.getParam("Text1justify").setAsAlias(param)
    del param
    param = groupText1.getParam("wrap")
    group.getParam("Text1wrap").setAsAlias(param)
    del param
    param = groupText1.getParam("align")
    group.getParam("Text1align").setAsAlias(param)
    del param
    param = groupText1.getParam("valign")
    group.getParam("Text1valign").setAsAlias(param)
    del param
    param = groupText1.getParam("name")
    group.getParam("Text1name").setAsAlias(param)
    del param
    param = groupText1.getParam("custom")
    group.getParam("Text1custom").setAsAlias(param)
    del param
    param = groupText1.getParam("font")
    group.getParam("Text1font").setAsAlias(param)
    del param
    param = groupText1.getParam("size")
    group.getParam("Text1size").setAsAlias(param)
    del param
    param = groupText1.getParam("color")
    group.getParam("Text1color").setAsAlias(param)
    del param
    param = groupText1.getParam("backgroundColor")
    group.getParam("Text1backgroundColor").setAsAlias(param)
    del param
    param = groupText1.getParam("letterSpace")
    group.getParam("Text1letterSpace").setAsAlias(param)
    del param
    param = groupText1.getParam("hintStyle")
    group.getParam("Text1hintStyle").setAsAlias(param)
    del param
    param = groupText1.getParam("hintMetrics")
    group.getParam("Text1hintMetrics").setAsAlias(param)
    del param
    param = groupText1.getParam("antialiasing")
    group.getParam("Text1antialiasing").setAsAlias(param)
    del param
    param = groupText1.getParam("subpixel")
    group.getParam("Text1subpixel").setAsAlias(param)
    del param
    param = groupText1.getParam("style")
    group.getParam("Text1style").setAsAlias(param)
    del param
    param = groupText1.getParam("weight")
    group.getParam("Text1weight").setAsAlias(param)
    del param
    param = groupText1.getParam("stretch")
    group.getParam("Text1stretch").setAsAlias(param)
    del param
    param = groupText1.getParam("strokeSize")
    group.getParam("Text1strokeSize").setAsAlias(param)
    del param
    param = groupText1.getParam("strokeColor")
    group.getParam("Text1strokeColor").setAsAlias(param)
    del param
    param = groupText1.getParam("strokeDash")
    group.getParam("Text1strokeDash").setAsAlias(param)
    del param
    param = groupText1.getParam("strokeDashPattern")
    group.getParam("Text1strokeDashPattern").setAsAlias(param)
    del param
    param = groupText1.getParam("circleRadius")
    group.getParam("Text1circleRadius").setAsAlias(param)
    del param
    param = groupText1.getParam("circleWords")
    group.getParam("Text1circleWords").setAsAlias(param)
    del param
    param = groupText1.getParam("arcRadius")
    group.getParam("Text1arcRadius").setAsAlias(param)
    del param
    param = groupText1.getParam("arcAngle")
    group.getParam("Text1arcAngle").setAsAlias(param)
    del param
    param = groupText1.getParam("scrollX")
    group.getParam("Text1scrollX").setAsAlias(param)
    del param
    param = groupText1.getParam("scrollY")
    group.getParam("Text1scrollY").setAsAlias(param)
    del param
    param = groupText1.getParam("frameRange")
    group.getParam("Text1frameRange").setAsAlias(param)
    del param
    param = groupText1.getParam("channels")
    group.getParam("Text1channels").setAsAlias(param)
    del param
    param = groupText1.getParam("processAllPlanes")
    group.getParam("Text1processAllPlanes").setAsAlias(param)
    del param

    try:
        extModule = sys.modules["TxtGroupExt"]
    except KeyError:
        extModule = None
    if extModule is not None and hasattr(extModule ,"createInstanceExt") and hasattr(extModule.createInstanceExt,"__call__"):
        extModule.createInstanceExt(app,group)
